export enum AuthenticationActions {
  SUCCESS_LOGIN = 'AUTHENTICATION_SUCCESS_LOGIN',
  FAIL_LOGIN = 'AUTHENTICATION_FAIL_LOGIN',
  SESSION_EXPIRED = 'AUTHENTICATION_SESSION_EXPIRED',
  UNAUTHORIZED = 'AUTHENTICATON_UNAUTHORIZED',
  LOGOUT = 'AUTHENTICATION_LOGOUT'
}
